### PR TITLE
Telemetry

### PR DESCRIPTION
**Pull request by carlpett**
Hi, 
I had a need for this functionality in a project, so I continued your on the work you did in [your PR](https://github.com/rackspace/gophercloud/pull/448). I rebased on upstream master and incorporated the suggested name changes. I also implemented the `Show` operation.

The PR looks a bit messy because of the rebase (since your fork/master isn't updated?), let me know if you'd rather I roll that part back (since it is all new code it is a clean rebase anyway).

### CODE REVIEW

**Comment by DSpeichert** [comment]
I've rebased my master to the newest version, please rebase you branch against that, so that we can have it all cleaner :)

**Comment by carlpett** [comment]
@DSpeichert Done!

**Comment by DSpeichert** [comment]
I've actually already rebased your changes in a way that avoided the merge altogether. It's in the original PR now https://github.com/rackspace/gophercloud/pull/448.

**Comment by carlpett** [comment]
Excellent, thanks!

**Pull request closed without merging**
